#161382387 add swagger (Api Documentation)
andela/ah-backend-thor pull request #30
Opened 2018-10-30 10:15 UTC by joshNic

#### What does this PR do?
Documents API using swagger
#### Description of Task to be completed?
- Description of Task to be completed?
- install the Django REST Swagger package which is a documentation Generator for Django REST Framework
- Add rest_framework_swagger on the list of installed apps
- Add schema view to the urls.py
- change from class-based views to generic views in authors/apps/authentication/views.py

#### How should this be manually tested?
- Run python manage.py
- Navigate to the browser then in the url type http://127.0.0.1:8000
#### Any background context you want to provide?
- When creating APIs, Swagger tooling may be used to automatically generate an Open API document based on the code itself.
- This is informally called code-first or bottom-up API development.
- Swagger allows connections directly to live APIs through an interactive, HTML-based user interface.
- Requests can be made directly from the UI and the options explored by the user of the interface.
#### What are the relevant pivotal tracker stories?
#161382387

2018-10-30 10:31 UTC, bozicschucky commented on authors/apps/authentication/views.py
> +# from rest_framework.views import APIView
why don't you remove the APIView since they are not being used?

2018-10-31 11:45 UTC, malep2007 requested changes
There are merge conflicts on the requirements file. Can you sort that out first?

2018-10-31 13:14 UTC, malep2007 commented
@joshNic the test coverage has reduced, but since the feature, you worked on does not entail coming up with new tests, this could be accepted.

2018-10-31 20:10 UTC, malep2007 approved these changes

2018-10-31 20:12 UTC, merged